[workspace]
resolver = "2" # What does this do?

[package]
name = "vger"
description = "2D GPU renderer for dynamic UIs"
version = "0.1.5"
license = "MIT"
readme = "README.md"
authors = ["Taylor Holliday <taylor@audulus.com>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/audulus/vger-rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
naga = { git = "https://github.com/audulus/naga", branch = "MSL-address-space-backport-v0.8" }

[dependencies]
wgpu = "0.12.0"
futures = "0.3"
euclid = "0.22.6"
png = "0.16"
fontdue = "0.7.2"
rect_packer = "0.2.1"
rand = "0.7.3"
